"""
NaviVision Studio (OpenDevelop) - Python / OpenCV Code Exporter
将界面可视化的算子流水线，自动导出为工业级可独立运行的 Python + OpenCV 生产脚本
"""

from typing import List, Dict, Any


def generate_python_code(steps: List[Dict[str, Any]], image_path_placeholder: str = "image.png") -> str:
    lines = [
        "#!/usr/bin/env python3",
        "# -*- coding: utf-8 -*-",
        '"""',
        "Auto-generated by NaviVision Studio (OpenDevelop - Free HDevelop Alternative)",
        "工业级机器视觉算法流水线独立可执行脚本",
        '"""',
        "",
        "import cv2",
        "import numpy as np",
        "import math",
        "",
        "def run_vision_pipeline(image_path: str):",
        f'    print(f"[Vision Engine] Processing: {{image_path}}")',
        "    # 1. 读取图像",
        "    image = cv2.imread(image_path)",
        "    if image is None:",
        "        raise FileNotFoundError(f'Cannot load image from {image_path}')",
        "    ",
        "    h, w = image.shape[:2]",
        "    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if len(image.shape) == 3 else image.copy()",
        "    current_mask = None",
        "    detected_objects = []",
        ""
    ]

    for idx, step in enumerate(steps):
        if not step.get("enabled", True):
            continue

        op = step["operator"]
        p = step.get("params", {})
        lines.append(f"    # --- 步骤 {idx + 1}: {op} ---")

        if op == "rgb1_to_gray":
            lines.append("    # 灰度化处理")
            lines.append("    # (已在初始化阶段转换)")
            lines.append("")

        elif op == "threshold":
            min_g = int(p.get("min_gray", 0))
            max_g = int(p.get("max_gray", 128))
            lines.append(f"    # 双阈值分割 (HALCON: threshold(Image, Region, {min_g}, {max_g}))")
            lines.append(f"    current_mask = cv2.inRange(gray, {min_g}, {max_g})")
            lines.append(f"    print(f'  [Threshold] Active pixels: {{np.count_nonzero(current_mask)}}')")
            lines.append("")

        elif op == "auto_threshold":
            inv = bool(p.get("invert", False))
            flag = "cv2.THRESH_BINARY_INV" if inv else "cv2.THRESH_BINARY"
            lines.append("    # Otsu 自适应大津法阈值分割")
            lines.append(f"    _, current_mask = cv2.threshold(gray, 0, 255, {flag} + cv2.THRESH_OTSU)")
            lines.append("")

        elif op == "morphology":
            op_type = str(p.get("op_type", "opening")).lower()
            shape = str(p.get("kernel_shape", "circle"))
            k_size = int(p.get("kernel_size", 5))
            shape_const = "cv2.MORPH_ELLIPSE" if shape == "circle" else ("cv2.MORPH_CROSS" if shape == "cross" else "cv2.MORPH_RECT")
            lines.append(f"    # 形态学运算 ({op_type}) 核大小: {k_size}")
            lines.append(f"    kernel = cv2.getStructuringElement({shape_const}, ({k_size}, {k_size}))")
            if op_type == "dilation":
                lines.append("    current_mask = cv2.dilate(current_mask, kernel)")
            elif op_type == "erosion":
                lines.append("    current_mask = cv2.erode(current_mask, kernel)")
            elif op_type == "opening":
                lines.append("    current_mask = cv2.morphologyEx(current_mask, cv2.MORPH_OPEN, kernel)")
            elif op_type == "closing":
                lines.append("    current_mask = cv2.morphologyEx(current_mask, cv2.MORPH_CLOSE, kernel)")
            lines.append("")

        elif op == "connection":
            conn = int(p.get("connectivity", 8))
            lines.append(f"    # 连通域打散分析 (HALCON: connection(Region, ConnectedRegions))")
            lines.append(f"    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(current_mask, connectivity={conn})")
            lines.append(f"    print(f'  [Connection] Found {{num_labels - 1}} independent connected regions')")
            lines.append("")

        elif op == "select_shape":
            min_area = int(p.get("min_area", 20))
            max_area = int(p.get("max_area", 999999))
            min_circ = float(p.get("min_circularity", 0.0))
            max_circ = float(p.get("max_circularity", 1.0))
            lines.append("    # 形状特征筛选 (HALCON: select_shape)")
            lines.append("    filtered_mask = np.zeros_like(current_mask)")
            lines.append("    # 提取并过滤连通对象")
            lines.append("    contours, _ = cv2.findContours(current_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)")
            lines.append("    matched_objects = []")
            lines.append("    for i, cnt in enumerate(contours):")
            lines.append("        area = cv2.contourArea(cnt)")
            lines.append("        perimeter = cv2.arcLength(cnt, True)")
            lines.append("        circularity = (4.0 * math.pi * area / (perimeter * perimeter)) if perimeter > 0 else 0.0")
            lines.append(f"        if {min_area} <= area <= {max_area} and {min_circ} <= circularity <= {max_circ}:")
            lines.append("            x, y, bw, bh = cv2.boundingRect(cnt)")
            lines.append("            matched_objects.append({'id': i, 'area': area, 'circularity': circularity, 'bbox': (x, y, bw, bh)})")
            lines.append("            cv2.drawContours(filtered_mask, [cnt], -1, 255, -1)")
            lines.append("    current_mask = filtered_mask")
            lines.append("    print(f'  [SelectShape] Retained {len(matched_objects)} qualified targets')")
            lines.append("")

        elif op == "edges_subpix":
            low_t = float(p.get("low_threshold", 30))
            high_t = float(p.get("high_threshold", 90))
            lines.append(f"    # 亚像素轮廓检测 (HALCON: edges_subpix - 梯度法向二次抛物线插值)")
            lines.append(f"    blurred = cv2.GaussianBlur(gray, (3, 3), 1.0)")
            lines.append(f"    edges = cv2.Canny(blurred, {int(low_t)}, {int(high_t)})")
            lines.append("    contours, _ = cv2.findContours(edges, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)")
            lines.append(f"    print(f'  [Edges] Extracted {{len(contours)}} subpixel XLD contours')")
            lines.append("")

        elif op == "measure_region":
            lines.append("    # 连通域特征几何度量 (HALCON: measure_region / smallest_rectangle2 / smallest_circle)")
            lines.append("    # 提取连通区域并计算重心、旋转外接矩形 OBB、外接圆与二阶矩主轴")
            lines.append("    contours, _ = cv2.findContours(current_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)")
            lines.append("    measurements = []")
            lines.append("    for i, cnt in enumerate(contours):")
            lines.append("        area = cv2.contourArea(cnt)")
            lines.append("        if area < 1: continue")
            lines.append("        rect = cv2.minAreaRect(cnt)")
            lines.append("        (cx, cy), radius = cv2.minEnclosingCircle(cnt)")
            lines.append("        m = cv2.moments(cnt)")
            lines.append("        orientation = 0.5 * math.atan2(2 * m['mu11'], m['mu20'] - m['mu02']) if m['m00'] > 0 else 0.0")
            lines.append("        measurements.append({")
            lines.append("            'id': i + 1, 'area': area, 'centroid': (round(cy, 2), round(cx, 2)),")
            lines.append("            'obb_center': (round(rect[0][1], 2), round(rect[0][0], 2)),")
            lines.append("            'obb_size': (round(rect[1][0], 2), round(rect[1][1], 2)),")
            lines.append("            'circle_radius': round(radius, 2), 'orientation_rad': round(orientation, 4)")
            lines.append("        })")
            lines.append("    print(f'  [Measure] Measured {len(measurements)} target regions with OBB & circles')")
            lines.append("")

    lines.extend([
        "    # 最终结果叠加呈现",
        "    result_overlay = image.copy()",
        "    if current_mask is not None:",
        "        # 半透明叠加掩膜 (RGBA 模拟 HALCON 显示)",
        "        colored_mask = np.zeros_like(image)",
        "        colored_mask[current_mask > 0] = [255, 240, 0] # 青蓝色高亮",
        "        result_overlay = cv2.addWeighted(result_overlay, 0.7, colored_mask, 0.3, 0)",
        "    ",
        "    return result_overlay",
        "",
        "if __name__ == '__main__':",
        f"    test_img = '{image_path_placeholder}'",
        "    try:",
        "        output = run_vision_pipeline(test_img)",
        "        cv2.imwrite('result_output.png', output)",
        "        print('[SUCCESS] Pipeline executed successfully, output saved to result_output.png')",
        "    except Exception as e:",
        "        print(f'[ERROR] Pipeline failed: {e}')",
        ""
    ])

    return "\n".join(lines)
